# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:14.6
    volumes:
    - './imgsmlr/:/imgsmlr/'
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080