version: '3.8'

services:
  localserver:
    image: nginx:1.25.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - local-nexus3
    networks:
      - nexus-network
    restart: always  # Auto-restart policy for localserver

  local-nexus3:
    image: sonatype/nexus3:3.62.0
    networks:
      - nexus-network
    volumes:
      - type: volume
        source: nexus-data
        target: /nexus-data
    restart: always  # Auto-restart policy for local-nexus3

networks:
  nexus-network:
    driver: bridge

volumes:
  nexus-data:
    name: nexus-data
